### ISSUE TITLE
User's cannot set their bio to be empty

### ISSUE THREAD

**Issue by not-a-code-cel** [Aevann1/Drama#12]
Clearing out the bio and saving it returns a white page with the json response of a 400 error that they made no changes. Further investigation:

https://github.com/Aevann1/Drama/blob/master/files/routes/settings.py#L65

Since the empty string is falsy in python, this code block will not be dropped in to, and this message is sent back. Perhaps a different way of testing whether the key is present can be used, at least for this key.

if key in dict:

**Comment by atrc445** [comment]
closing because of #13
