### ISSUE TITLE
[Bug] 2FA Removal Links "Inactive" - Don't Remove 2FA

### ISSUE THREAD

**Issue by Jimmerz28** [Aevann1/Drama#3]
When attempting to remove 2FA from an account the links redirect to an "Inactive Link" page.

Steps to reproduce:

1. Navigate to https://rdrama.net/login
2. Login with username and password
3. Click "Lost your 2FA device?"
4. Get redirected to https://rdrama.net/lost_2fa
5. Enter correct information
6. Recieve email with reset link
7. Reset Link links to https://rdrama.net/reset_2fa with the following query params:
    * id
    * t
    * token
8. Page displays "Inactive Link That link isn't active yet. Try again later."

🧹🧹🧹🧹

**Comment by Aevann1** [comment]
fixed 🧹 🧹

**Comment by Jimmerz28** [comment]
Confirmed the fix! Thanks Jannie!

**Comment by Aevann1** [comment]
np sweetie 😘
