### ISSUE TITLE
Use lightweight .webp and .mp4 for images and gifs/videos

### ISSUE THREAD

**Issue by ghbung** [Aevann1/Drama#38]
Imgur has support for .mp4 and .webp built in and can shrink images from 25% to 90%. Some examples would be:
https://i.imgur.com/OcnNvsK.gif -> https://i.imgur.com/OcnNvsK.mp4 (541.17kb -> 90.26kb)
https://i.imgur.com/SqiFH2G_d.png?maxwidth=9999 -> https://i.imgur.com/SqiFH2G_d.webp?maxwidth=9999 (1145kb -> 175kb)
Swapping the image we receive should be as easy as changing the extension in the URL, since Imgur should convert to those files anyway. I have yet to test for a larger batch of data than just the above.

Lighthouse claims that this should save a few seconds off of the load time, especially for the front page.

**Comment by Aevann1** [comment]
done, thank you so much

**Comment by Aevann1** [comment]
tell me ur username on the site if u want the "ideamaker" badge

**Comment by ghbung** [comment]
https://rdrama.net/@bung
