### ISSUE TITLE
Problematic terms and fostering inclusion

### ISSUE THREAD

**Issue by TheCaringCleaner** [Aevann1/Drama#43]
Hey y’all, I like to think of myself as a community guardian - which means I may lack the technical skills required to do little things like write code, but I can help ensure that the big things are take care of: like ensuring that the code you write isn’t problematic and that it encourages inclusion.

As a community, FOSS maintainers (or as they’re correctly termed: “_voluntary code janitorial staff_”) have a duty to minimise harm and foster inclusive environments for people of all backgrounds and abilities.

There are now complex cutting-edge tools available that can actually *search text files* - and as a result they can solve these very troubling problems. I suggest https://github.com/get-woke/woke 

Please clean the codebase of problematic references and consider introducing a code of conduct that ensures the safety of all marginalised peoples: you 👏 must 👏 do 👏 better 👏.

**Comment by Aevann1** [comment]
lol

**Comment by DuffyElmer** [comment]
lmao what a fuckin project
