### ISSUE TITLE
Cannot register new account due to broken CAPTCHA module

### ISSUE THREAD

**Issue by DuffyElmer** [Aevann1/Drama#54]
![image](https://user-images.githubusercontent.com/28229677/134817613-bf4c846b-9d52-45b5-9bdb-c83bbfb64272.png)

![image](https://user-images.githubusercontent.com/28229677/134817634-3484cb52-ee9c-47f5-a1a9-ff7d3e316aad.png)

Looks like you didn't include your hcaptcha sitekey, the instructions for getting it are here:

https://docs.hcaptcha.com/#add-the-hcaptcha-widget-to-your-webpage

**Comment by Aevann1** [comment]
fixed, thx
