### ISSUE TITLE
Use CDATA instead of escaping everything in RSS feed

### ISSUE THREAD

**Issue by architectdrone** [Aevann1/Drama#61]
In the [rss feed](https://rdrama.net/rss/top/today), we escape everything in the content field by converting all "<" to "&lt" and all ">" to "&gt". Lol, why would you do that when you could just wrap it in a [CDATA](https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean) tag like every other RSS feed. For example, see [Landchad.net's RSS feed](https://landchad.net/rss.xml). This is nice because feed readers know how to handle it instead of sperging out and showing the html tags. For example (in commafeed), the average escaped bracket fan
![image](https://user-images.githubusercontent.com/17835256/135107562-451d970b-1505-40dd-bf5f-d41f93e27a92.png)
vs the average CDATA enjoyer
![image](https://user-images.githubusercontent.com/17835256/135107655-46067123-d89a-4706-a865-db6a58f88f1f.png)

Pretty sure that all that needs to change is [this line](https://github.com/Aevann1/Drama/blob/99eb6ae9c036f2ab28d1f3d45afff50be672c5cb/files/routes/feeds.py#L65), so I will test out the change when I get home tonight, I just wanted to know if that would cause any problems for anyone.

**Comment by architectdrone** [comment]
Here's the PR that added the change https://github.com/ruqqus/ruqqus/pull/750

**Comment by Aevann1** [comment]
could u make a PR when ur free pls

**Comment by architectdrone** [comment]
sure
