### ISSUE TITLE
Grant me access to the repo pls

### ISSUE THREAD

**Issue by architectdrone** [Aevann1/Drama#63]
I have a feature to make a PR for, but I don't think I have permission to push. The change is a 1-liner in feeds.py:
from
```
if len(post.body_html) > 0:
	with tag("content", type="html"):
		text(html.escape(f'<img loading="lazy" src={image_url}/><br/>{post.body_html}'))
```
to
```
if len(post.body_html) > 0:
	with tag("content", type="html"):
		doc.cdata(f'<img loading="lazy" src={image_url}/><br/>{post.body_html}')
```
I tested this change out and it works, but I just can't open a PR.

**Comment by Aevann1** [comment]
added ur change, thanks!

sorry for not getting back to u earlier

**Comment by architectdrone** [comment]
Np dawg thanks :)
