### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [Aevann1/Drama#8]
.

**Comment by Aevann1** [comment]
hello friend, that's a great idea

for now, I disabled most of the flashy lights in the "Midnight" theme, I'll implement the rest later once I'm free again inshallah

**Comment by Dramanaut** [comment]
thx fren,

Already seems faster (but that might be placebo). As a suggestion, maybe removing the trans banner (which, afaik, is to keep them out), link previews, the drama link gif and flairs itself.

**Comment by Dramanaut** [comment]
Um, accidentally closed it.

**Comment by Aevann1** [comment]
yessir, will do
