### ISSUE TITLE
teddit.net redirect?

### ISSUE THREAD

**Issue by r3muxd** [Aevann1/Drama#99]
the mobile reddit website is practically unusable and keeps screaming at you to download the app

maybe there could be a teddit.net redirect option like there is for nitter right now?

**Comment by TheCaringCleaner** [comment]
Agreed that reddit is completely unusable on mobile - especially if something has been marked as NSFW. I'm not sure how the referrer is handled either, and whether that will would be used for fingerprinting/attributing traffic.

If @Aevann1 is happy, then I've done a quick PR with a nitter style option - #102
